# Pet Shelter Analysis

In [24]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [25]:
intakes = pd.read_csv('aac_intakes.csv')
outcomes = pd.read_csv('aac_outcomes.csv')
intakes_and_outcomes = pd.read_csv('aac_intakes_outcomes.csv')

In [26]:
intakes.head()

,age_upon_intake,animal_id,animal_type,breed,color,datetime,datetime2,found_location,intake_condition,intake_type,name,sex_upon_intake
0,8 years,A706918,Dog,English Springer Spaniel,White/Liver,2015-07-05T12:59:00.000,2015-07-05T12:59:00.000,9409 Bluegrass Dr in Austin (TX),Normal,Stray,Belle,Spayed Female
1,11 months,A724273,Dog,Basenji Mix,Sable/White,2016-04-14T18:43:00.000,2016-04-14T18:43:00.000,2818 Palomino Trail in Austin (TX),Normal,Stray,Runster,Intact Male
2,4 weeks,A665644,Cat,Domestic Shorthair Mix,Calico,2013-10-21T07:59:00.000,2013-10-21T07:59:00.000,Austin (TX),Sick,Stray,NaN,Intact Female
3,4 years,A682524,Dog,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,2014-06-29T10:38:00.000,2014-06-29T10:38:00.000,800 Grove Blvd in Austin (TX),Normal,Stray,Rio,Neutered Male
4,2 years,A743852,Dog,Labrador Retriever Mix,Chocolate,2017-02-18T12:46:00.000,2017-02-18T12:46:00.000,Austin (TX),Normal,Owner Surrender,Odin,Neutered Male

In [27]:

intakes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80187 entries, 0 to 80186
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age_upon_intake   80187 non-null  object
 1   animal_id         80187 non-null  object
 2   animal_type       80187 non-null  object
 3   breed             80187 non-null  object
 4   color             80187 non-null  object
 5   datetime          80187 non-null  object
 6   datetime2         80187 non-null  object
 7   found_location    80187 non-null  object
 8   intake_condition  80187 non-null  object
 9   intake_type       80187 non-null  object
 10  name              55603 non-null  object
 11  sex_upon_intake   80186 non-null  object
dtypes: object(12)
memory usage: 7.3+ MB

In [28]:
outcomes.head()

,age_upon_outcome,animal_id,animal_type,breed,color,date_of_birth,datetime,monthyear,name,outcome_subtype,outcome_type,sex_upon_outcome
0,2 weeks,A684346,Cat,Domestic Shorthair Mix,Orange Tabby,2014-07-07T00:00:00,2014-07-22T16:04:00,2014-07-22T16:04:00,NaN,Partner,Transfer,Intact Male
1,1 year,A666430,Dog,Beagle Mix,White/Brown,2012-11-06T00:00:00,2013-11-07T11:47:00,2013-11-07T11:47:00,Lucy,Partner,Transfer,Spayed Female
2,1 year,A675708,Dog,Pit Bull,Blue/White,2013-03-31T00:00:00,2014-06-03T14:20:00,2014-06-03T14:20:00,*Johnny,NaN,Adoption,Neutered Male
3,9 years,A680386,Dog,Miniature Schnauzer Mix,White,2005-06-02T00:00:00,2014-06-15T15:50:00,2014-06-15T15:50:00,Monday,Partner,Transfer,Neutered Male
4,5 months,A683115,Other,Bat Mix,Brown,2014-01-07T00:00:00,2014-07-07T14:04:00,2014-07-07T14:04:00,NaN,Rabies Risk,Euthanasia,Unknown

In [29]:
outcomes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80681 entries, 0 to 80680
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age_upon_outcome  80673 non-null  object
 1   animal_id         80681 non-null  object
 2   animal_type       80681 non-null  object
 3   breed             80681 non-null  object
 4   color             80681 non-null  object
 5   date_of_birth     80681 non-null  object
 6   datetime          80681 non-null  object
 7   monthyear         80681 non-null  object
 8   name              56116 non-null  object
 9   outcome_subtype   36893 non-null  object
 10  outcome_type      80667 non-null  object
 11  sex_upon_outcome  80679 non-null  object
dtypes: object(12)
memory usage: 7.4+ MB

In [30]:
intakes_and_outcomes.head()

,age_upon_outcome,animal_id_outcome,date_of_birth,outcome_subtype,outcome_type,sex_upon_outcome,age_upon_outcome_(days),age_upon_outcome_(years),age_upon_outcome_age_group,outcome_datetime,...,age_upon_intake_age_group,intake_datetime,intake_month,intake_year,intake_monthyear,intake_weekday,intake_hour,intake_number,time_in_shelter,time_in_shelter_days
0,10 years,A006100,2007-07-09 00:00:00,NaN,Return to Owner,Neutered Male,3650,10.0,"(7.5, 10.0]",2017-12-07 14:07:00,...,"(7.5, 10.0]",2017-12-07 00:00:00,12,2017,2017-12,Thursday,14,1.0,0 days 14:07:00.000000000,0.588194
1,7 years,A006100,2007-07-09 00:00:00,NaN,Return to Owner,Neutered Male,2555,7.0,"(5.0, 7.5]",2014-12-20 16:35:00,...,"(5.0, 7.5]",2014-12-19 10:21:00,12,2014,2014-12,Friday,10,2.0,1 days 06:14:00.000000000,1.259722
2,6 years,A006100,2007-07-09 00:00:00,NaN,Return to Owner,Neutered Male,2190,6.0,"(5.0, 7.5]",2014-03-08 17:10:00,...,"(5.0, 7.5]",2014-03-07 14:26:00,3,2014,2014-03,Friday,14,3.0,1 days 02:44:00.000000000,1.113889
3,10 years,A047759,2004-04-02 00:00:00,Partner,Transfer,Neutered Male,3650,10.0,"(7.5, 10.0]",2014-04-07 15:12:00,...,"(7.5, 10.0]",2014-04-02 15:55:00,4,2014,2014-04,Wednesday,15,1.0,4 days 23:17:00.000000000,4.970139
4,16 years,A134067,1997-10-16 00:00:00,NaN,Return to Owner,Neutered Male,5840,16.0,"(15.0, 17.5]",2013-11-16 11:54:00,...,"(15.0, 17.5]",2013-11-16 09:02:00,11,2013,2013-11,Saturday,9,1.0,0 days 02:52:00.000000000,0.119444

In [31]:
intakes_and_outcomes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79672 entries, 0 to 79671
Data columns (total 41 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   age_upon_outcome            79672 non-null  object
 1   animal_id_outcome           79672 non-null  object
 2   date_of_birth               79672 non-null  object
 3   outcome_subtype             36348 non-null  object
 4   outcome_type                79662 non-null  object
 5   sex_upon_outcome            79671 non-null  object
 6   age_upon_outcome_(days)     79672 non-null  int64
 7   age_upon_outcome_(years)    79672 non-null  float64
 8   age_upon_outcome_age_group  79672 non-null  object
 9   outcome_datetime            79672 non-null  object
 10  outcome_month               79672 non-null  int64
 11  outcome_year                79672 non-null  int64
 12  outcome_monthyear           79672 non-null  object
 13  outcome_weekday             79672 non-null  object
 14  outcome_hour                79672 non-null  int64
 15  outcome_number              79672 non-null  float64
 16  dob_year                    79672 non-null  int64
 17  dob_month                   79672 non-null  int64
 18  dob_monthyear               79672 non-null  object
 19  age_upon_intake             79672 non-null  object
 20  animal_id_intake            79672 non-null  object
 21  animal_type                 79672 non-null  object
 22  breed                       79672 non-null  object
 23  color                       79672 non-null  object
 24  found_location              79672 non-null  object
 25  intake_condition            79672 non-null  object
 26  intake_type                 79672 non-null  object
 27  sex_upon_intake             79671 non-null  object
 28  count                       79672 non-null  int64
 29  age_upon_intake_(days)      79672 non-null  int64
 30  age_upon_intake_(years)     79672 non-null  float64
 31  age_upon_intake_age_group   79672 non-null  object
 32  intake_datetime             79672 non-null  object
 33  intake_month                79672 non-null  int64
 34  intake_year                 79672 non-null  int64
 35  intake_monthyear            79672 non-null  object
 36  intake_weekday              79672 non-null  object
 37  intake_hour                 79672 non-null  int64
 38  intake_number               79672 non-null  float64
 39  time_in_shelter             79672 non-null  object
 40  time_in_shelter_days        79672 non-null  float64
dtypes: float64(5), int64(11), object(25)
memory usage: 24.9+ MB

# Is there an area where more pets are found?
Upon 36576 unique locations in the dataset, the area with the most found animals is Austin(TX) with 14,311 animals.
I did this by applying value_counts on the 'found_location' column. And by default it sort values in descending order.

In [32]:
# locations = intakes_and_outcomes['found_location'].nunique() # to find the unique location in the dataset
# locations ## the number of locations in the datasets is 36576

In [33]:
animals_location = intakes_and_outcomes['found_location'].value_counts()
animals_location.head()

found_location
Austin (TX)                          14311
Outside Jurisdiction                   945
Travis (TX)                            907
7201 Levander Loop in Austin (TX)      514
Del Valle (TX)                         407
Name: count, dtype: int64

# What is the average number of pets found in a month in the year 2015?
The average number of pets found in a month in the year 2015 is 1558.
First, I filtered the dataset per intake year which is 2015. i counted the values per intake month and use the mean function
# Are there months where there is a higher number of animals found? 
Yes.
There is a higher  number of animals found within the following months; May, June, July, August, September and October. These months have a high number of found animals higher than the average which is 1558.
I achieved this by comparing the number of found animals in each month with the average.

In [34]:
pets_2015 = intakes_and_outcomes[intakes_and_outcomes['intake_year'] == 2015]
monthly_totals = pets_2015['intake_month'].value_counts()
average_intake = monthly_totals.mean()
average_intake

above_average_months = monthly_totals[monthly_totals.values > average_intake]
above_average_months.sort_index()

intake_month
5     2092
6     2188
7     1634
8     1717
9     1590
10    1738
Name: count, dtype: int64

# What is the ratio of incoming pets vs. adopted pets?
The ratio of incoming pets vs adopted pets is 2. Meaning for a every 2 pets that enter the shelter only one pet is adopted.
i did this by counting the number of adopted pets and intake pets and dividing the number of incoming pets by the number of adopted pets(number of incoming_pets / number of adopted_pets)

In [35]:
adopted_pets = intakes_and_outcomes[intakes_and_outcomes['outcome_type'] =='Adoption']
num_adopted_pets = len(adopted_pets)
incoming_pets = len(intakes)
ratio = incoming_pets / num_adopted_pets
round(ratio)

2

# What is the distribution of the types of animals in the shelter?
As we can see below the animal type and their respective number. The most common animal found in the shelter is Dog.
I achieved this by grouping all the animal types in the shelter and aggregating(count) according to their type or kind.

In [36]:
animal_distribution = intakes_and_outcomes.groupby('animal_type').agg({'animal_id_intake': 'count'})
animal_distribution.columns = ['Number of types of animals in the shelter']
animal_distribution  = animal_distribution.reset_index()
animal_distribution

  animal_type  Number of types of animals in the shelter
0        Bird                                        339
1         Cat                                      29539
2         Dog                                      45366
3       Other                                       4428

# What are the adoption rates for specific breeds?
The top 5 Breed of Dogs are Labrador Retriever Mix, Pit Bull Mix,Chihuahua Shorthair Mix, 
German Shepherd mix and Austrilain cattle Dog Mix. Among the 5 top breed of dogs, Ladbrador Retriever Mix being the most adopted breed with  **23,688** number of adoption, with a percentage of **27.9%**.
I achieved this by first filtering dataset, the columns; animal_type and the outcome_type to be dog and adoption respectively.
After finding dogs who are adopted, i further grouped them per breed and aggregated them using the count function.
I then sorted the values in respect to their number of adoption.
Secondly, to find the ratio, I created another column by dividing (the number of adoption / the sum of adoption) and multiplying 
it by 100 to find percentage.

In [37]:
dogs = intakes_and_outcomes[intakes_and_outcomes['animal_type'] == 'Dog']
adoption = dogs[dogs['outcome_type'] == 'Adoption']
breed = adoption.groupby('breed').agg({'animal_id_intake': 'count'})
breed.columns = ['number of adoption']
breed = breed.reset_index()
top_breeds = breed.sort_values(by='number of adoption', ascending=False)
top_breeds['percentage'] = round((top_breeds['number of adoption'] / top_breeds['number of adoption'].sum()) * 100,1)

top_breeds[:5]

                          breed  number of adoption  percentage
832      Labrador Retriever Mix                2368        11.5
1048               Pit Bull Mix                2324        11.3
455     Chihuahua Shorthair Mix                2270        11.0
684         German Shepherd Mix                 922         4.5
70    Australian Cattle Dog Mix                 607         2.9

# What are the adoption rate for different colorings?
The top 5 adoption rate for different colorings are below.
black/white being the most favourite color of adoption number **3,738** and adoption rate of  **11.1%**.
And brown/white being the least among the 5 colorings. I achieved this by filtering the column(outcome_type) of the dataset to adoption and grouping it according to their color and using the aggregate(count) function on them.
I then created another column to find the percentage by (number of colors / the sum of number of colors) and multiplying the
results by 100.

In [38]:
animals_adopted = intakes_and_outcomes[intakes_and_outcomes['outcome_type'] == 'Adoption']
coloring = animals_adopted.groupby('color').agg({'animal_id_intake': 'count'})
coloring.columns = ['num of colors']
coloring = coloring.reset_index()
top_coloring = coloring.sort_values(by='num of colors', ascending=False)
top_coloring['percentage'] = round((top_coloring['num of colors'] / top_coloring['num of colors'].sum()) * 100,1)
top_5 = top_coloring[:5]
top_5

           color  num of colors  percentage
34   Black/White           3738        11.1
5          Black           2692         8.0
105  Brown Tabby           1871         5.6
313    Tan/White           1163         3.5
132  Brown/White           1110         3.3

# About how many animals are spayed/neutered each month?
About 4,085 animals are spayed/neutered each month. I did this by filtering the column(sex_upon_intake) to intact male or intact female,
after, I grouped the newly filtered dataset into intake month and counted the animal_id_intake column.

In [49]:
male_female_intact = intakes_and_outcomes[(intakes_and_outcomes['sex_upon_intake'] == 'Intact Female') | (intakes_and_outcomes['sex_upon_intake']=='Intact Male')]
each_month = male_female_intact.groupby('intake_month').agg({'animal_id_intake': 'count'})
average_per_month = round(each_month['animal_id_intake'].mean())
average_per_month

4085